-- src/render/tag_icons.lua
-- DATA-ONLY icon registry for keyword/tag text. Source grids mirror
-- docs/generation/generateur-icones-tags.html so card chips and inline
-- keywords share the same small silhouettes.

local I = {
  poison = {
    "   m    ",
    "  hm    ",
    "  hmm   ",
    " hmomd  ",
    " hmmmd  ",
    " dmmmd  ",
    "  ddd   ",
    "        ",
  },
  bleed = {
    "   d    ",
    "   m    ",
    "   m    ",
    "  hmm   ",
    " hmmmd  ",
    " hmmmd  ",
    "  ddd   ",
    "        ",
  },
  burn = {
    "   h    ",
    "  hm    ",
    "  mhm   ",
    " dmhm   ",
    " mhmhm  ",
    " mmhmm  ",
    "  ddd   ",
    "        ",
  },
  rot = {
    "  ddd   ",
    " dmmmd  ",
    " momom  ",
    " dmmmd  ",
    " dmdmd  ",
    "  ddd   ",
    "        ",
    "        ",
  },
  shock = {
    "   hh   ",
    "  hd    ",
    " hh     ",
    " hhhh   ",
    "   hh   ",
    "  hd    ",
    " hd     ",
    "        ",
  },

  shield = {
    " dmmmmd ",
    " mhhhhm ",
    " mhmmhm ",
    " mhmmhm ",
    " dmmmmd ",
    "  dmmd  ",
    "   dd   ",
    "        ",
  },
  heal = {
    "   hh   ",
    "   mm   ",
    " hhmmhh ",
    " mmmmmm ",
    "   mm   ",
    "   dd   ",
    "        ",
    "        ",
  },
  regen = {
    " mm mm  ",
    "mhmmhm  ",
    "mmmmmm  ",
    " mmmm   ",
    "  mm    ",
    "   d    ",
    "        ",
    "        ",
  },
  thorns = {
    "  m m   ",
    " hmhm   ",
    "  mmm   ",
    "hmmmmh  ",
    "  mmm   ",
    " dmhmd  ",
    "  d d   ",
    "        ",
  },
  taunt = {
    " mmmmm  ",
    " mohom  ",
    " mmmmm  ",
    " mhhhm  ",
    " dmmmd  ",
    "  d d   ",
    "        ",
    "        ",
  },
  empower = {
    "   h    ",
    "  hmh   ",
    " hmmmh  ",
    "hmmmmmh ",
    "   m    ",
    "   m    ",
    "  ddd   ",
    "        ",
  },
  guard = {
    " m m m  ",
    " mmmmm  ",
    " mhhhm  ",
    " mhdhm  ",
    " mhhhm  ",
    " mmmmm  ",
    "  ddd   ",
    "        ",
  },
  growth = {
    "  h h   ",
    " hmhm   ",
    "  hmh   ",
    "   m    ",
    "   m    ",
    "  dmd   ",
    "  ddd   ",
    "        ",
  },
  execute = {
    " h   h  ",
    " hmmmh  ",
    "  dmd   ",
    "  dmd   ",
    "  dmd   ",
    "   m    ",
    "   d    ",
    "        ",
  },
  crit = {
    "   h    ",
    " d hh d ",
    "  hoh   ",
    "hhomohh ",
    "  hoh   ",
    " d hh d ",
    "   d    ",
    "        ",
  },
  cleave = {
    "    hhh ",
    "   hhd  ",
    "  hhd   ",
    " hhd    ",
    " hd     ",
    " d      ",
    "        ",
    "        ",
  },
  strip_shield = {
    " dmmmd  ",
    " mhhhm  ",
    " mhmhm  ",
    " dmmmd  ",
    "  ddd   ",
    "  o o   ",
    "   o    ",
    "        ",
  },
  vulnerable = {
    " dmmmd  ",
    " mhdhm  ",
    " mmdmm  ",
    " mhdhm  ",
    " dmdmd  ",
    "  d d   ",
    "        ",
    "        ",
  },
  weaken = {
    "   m    ",
    "   m    ",
    "   m    ",
    " hmmmh  ",
    "  hmh   ",
    "   h    ",
    "  d d   ",
    "        ",
  },

  aura = {
    "  mmm   ",
    " m d m  ",
    " m m m  ",
    " m o m  ",
    " m m m  ",
    " m d m  ",
    "  mmm   ",
    "        ",
  },
  commander = {
    "d m m d ",
    "mhmhmhm ",
    "mmmmmmm ",
    "mhmmhmm ",
    "mmommmm ",
    " ddddd  ",
    "        ",
    "        ",
  },
  whisper = {
    "        ",
    " dmmmd  ",
    "omhhhmo ",
    " dmmmd  ",
    "   d    ",
    "        ",
    "        ",
    "        ",
  },
  multicast = {
    " o      ",
    "oho  o  ",
    " o  oho ",
    "     o  ",
    "  o     ",
    " oho    ",
    "  o     ",
    "        ",
  },
  haste = {
    "h   h   ",
    " h   h  ",
    "  h   h ",
    " h   h  ",
    "h   h   ",
    "        ",
    "        ",
    "        ",
  },

  ahead = {
    "  h     ",
    "  hhh   ",
    "  hhhhh ",
    "  hhhhhh",
    "  hhhhh ",
    "  hhh   ",
    "  h     ",
    "        ",
  },
  behind = {
    "     h  ",
    "   hhh  ",
    " hhhhh  ",
    "hhhhhh  ",
    " hhhhh  ",
    "   hhh  ",
    "     h  ",
    "        ",
  },
  above = {
    "   h    ",
    "  hhh   ",
    "  hhh   ",
    " hhhhh  ",
    " hhhhh  ",
    "hhhhhhh ",
    "hhhhhhh ",
    "        ",
  },
  below = {
    "mmmmmmm ",
    "mmmmmmm ",
    " mmmmm  ",
    " mmmmm  ",
    "  mmm   ",
    "  mmm   ",
    "   m    ",
    "        ",
  },

  summon = {
    "   o    ",
    "  hmh   ",
    " hmmmh  ",
    "hmmmmmh ",
    " o   o  ",
    " dmmmd  ",
    "  ddd   ",
    "        ",
  },
  mimicry = {
    " mmmm   ",
    " mhhm   ",
    " mhmmmm ",
    " mmmhhm ",
    "   mhhm ",
    "   mmmm ",
    "        ",
    "        ",
  },
  type = {
    " ommmm  ",
    " mmmmmd ",
    " mhhhmd ",
    " mmmmmd ",
    " mhhhmd ",
    " mmmmmd ",
    "  dddd  ",
    "        ",
  },
}

I.faint = I.rot

return I
